// Generated by the Processing.js exporter for Processing IDE.
// https://github.com/fjenett/processingjstool

// this code was autogenerated from PJS
(function($p) {

function setup() {
$p.size(200,200);
  $p.background(100);
  $p.stroke(255);
  $p.ellipse(50,50,25,25);
  $p.println("Hello Web!");
}
$p.setup = setup;

})